language: python
os: linux
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

jobs:
  include:
    - stage: combine coverage files
      python: 3.7
      script: .travis/gen_report.sh

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install -U pytest
  - pip install -U pytest-cov

install:
  - pip install .

script:
  # run all tests including those cases may take long time
  - .travis/runtests.sh
