language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

matrix:
  include:
  - name: "Python 3.4"
    python: 3.4
  - name: "Python 3.5"
    python: 3.5
  - name: "Python 3.6"
    python: 3.6
  - name: "Python 3.7"
    python: 3.7

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install -U pytest

install:
  - pip install .

script:
  # run all tests including those cases may take long time
  - python -m pytest ./tests/ --runslow
