language: python
os: linux
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

cache:
  directories:
    - $HOME/.cache/pip
  pip: true

# Hosting service for report is switched to codecov.io
# jobs:
#   include:
#     - stage: combine coverage files
#       python: 3.7
#       script: .travis/gen_report.sh

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov

install:
  - pip install .

script:
  # Run all tests including those cases may take long time
  # (switch to codecov)
  - .travis/runtests_codecov.sh

after_success:
  # Upload .coverage file
  - codecov
